// Generated by gencpp from file test_service_client/num.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_CLIENT_MESSAGE_NUM_H
#define TEST_SERVICE_CLIENT_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_service_client
{
template <class ContainerAllocator>
struct num_
{
  typedef num_<ContainerAllocator> Type;

  num_()
    : num(0.0)  {
    }
  num_(const ContainerAllocator& _alloc)
    : num(0.0)  {
  (void)_alloc;
    }



   typedef double _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::test_service_client::num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_service_client::num_<ContainerAllocator> const> ConstPtr;

}; // struct num_

typedef ::test_service_client::num_<std::allocator<void> > num;

typedef boost::shared_ptr< ::test_service_client::num > numPtr;
typedef boost::shared_ptr< ::test_service_client::num const> numConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_service_client::num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_service_client::num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_service_client::num_<ContainerAllocator1> & lhs, const ::test_service_client::num_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_service_client::num_<ContainerAllocator1> & lhs, const ::test_service_client::num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_service_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_service_client::num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service_client::num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_service_client::num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f942a3e0cbd340847b2a0e5b31a783fe";
  }

  static const char* value(const ::test_service_client::num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf942a3e0cbd34084ULL;
  static const uint64_t static_value2 = 0x7b2a0e5b31a783feULL;
};

template<class ContainerAllocator>
struct DataType< ::test_service_client::num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_service_client/num";
  }

  static const char* value(const ::test_service_client::num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_service_client::num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 num\n"
"\n"
;
  }

  static const char* value(const ::test_service_client::num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_service_client::num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_service_client::num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_service_client::num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<double>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERVICE_CLIENT_MESSAGE_NUM_H
