// Generated by gencpp from file test_service_client/sum_two_numsRequest.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMSREQUEST_H
#define TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_service_client
{
template <class ContainerAllocator>
struct sum_two_numsRequest_
{
  typedef sum_two_numsRequest_<ContainerAllocator> Type;

  sum_two_numsRequest_()
    : a(0.0)
    , b(0.0)  {
    }
  sum_two_numsRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sum_two_numsRequest_

typedef ::test_service_client::sum_two_numsRequest_<std::allocator<void> > sum_two_numsRequest;

typedef boost::shared_ptr< ::test_service_client::sum_two_numsRequest > sum_two_numsRequestPtr;
typedef boost::shared_ptr< ::test_service_client::sum_two_numsRequest const> sum_two_numsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_service_client::sum_two_numsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_service_client::sum_two_numsRequest_<ContainerAllocator1> & lhs, const ::test_service_client::sum_two_numsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_service_client::sum_two_numsRequest_<ContainerAllocator1> & lhs, const ::test_service_client::sum_two_numsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_service_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f4f9f1b571de73ae8592a1438fd23f3";
  }

  static const char* value(const ::test_service_client::sum_two_numsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f4f9f1b571de73aULL;
  static const uint64_t static_value2 = 0xe8592a1438fd23f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_service_client/sum_two_numsRequest";
  }

  static const char* value(const ::test_service_client::sum_two_numsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n"
"float64 b\n"
;
  }

  static const char* value(const ::test_service_client::sum_two_numsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sum_two_numsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_service_client::sum_two_numsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_service_client::sum_two_numsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMSREQUEST_H
