// Generated by gencpp from file test_service_client/sum_two_nums.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMS_H
#define TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMS_H

#include <ros/service_traits.h>


#include <test_service_client/sum_two_numsRequest.h>
#include <test_service_client/sum_two_numsResponse.h>


namespace test_service_client
{

struct sum_two_nums
{

typedef sum_two_numsRequest Request;
typedef sum_two_numsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sum_two_nums
} // namespace test_service_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_service_client::sum_two_nums > {
  static const char* value()
  {
    return "eb3958e9614615192c3e63bd0b5590df";
  }

  static const char* value(const ::test_service_client::sum_two_nums&) { return value(); }
};

template<>
struct DataType< ::test_service_client::sum_two_nums > {
  static const char* value()
  {
    return "test_service_client/sum_two_nums";
  }

  static const char* value(const ::test_service_client::sum_two_nums&) { return value(); }
};


// service_traits::MD5Sum< ::test_service_client::sum_two_numsRequest> should match
// service_traits::MD5Sum< ::test_service_client::sum_two_nums >
template<>
struct MD5Sum< ::test_service_client::sum_two_numsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_service_client::sum_two_nums >::value();
  }
  static const char* value(const ::test_service_client::sum_two_numsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service_client::sum_two_numsRequest> should match
// service_traits::DataType< ::test_service_client::sum_two_nums >
template<>
struct DataType< ::test_service_client::sum_two_numsRequest>
{
  static const char* value()
  {
    return DataType< ::test_service_client::sum_two_nums >::value();
  }
  static const char* value(const ::test_service_client::sum_two_numsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_service_client::sum_two_numsResponse> should match
// service_traits::MD5Sum< ::test_service_client::sum_two_nums >
template<>
struct MD5Sum< ::test_service_client::sum_two_numsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_service_client::sum_two_nums >::value();
  }
  static const char* value(const ::test_service_client::sum_two_numsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service_client::sum_two_numsResponse> should match
// service_traits::DataType< ::test_service_client::sum_two_nums >
template<>
struct DataType< ::test_service_client::sum_two_numsResponse>
{
  static const char* value()
  {
    return DataType< ::test_service_client::sum_two_nums >::value();
  }
  static const char* value(const ::test_service_client::sum_two_numsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMS_H
