// Generated by gencpp from file test_service_client/sum_two_numsResponse.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMSRESPONSE_H
#define TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_service_client
{
template <class ContainerAllocator>
struct sum_two_numsResponse_
{
  typedef sum_two_numsResponse_<ContainerAllocator> Type;

  sum_two_numsResponse_()
    : sum(0.0)  {
    }
  sum_two_numsResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef double _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sum_two_numsResponse_

typedef ::test_service_client::sum_two_numsResponse_<std::allocator<void> > sum_two_numsResponse;

typedef boost::shared_ptr< ::test_service_client::sum_two_numsResponse > sum_two_numsResponsePtr;
typedef boost::shared_ptr< ::test_service_client::sum_two_numsResponse const> sum_two_numsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_service_client::sum_two_numsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_service_client::sum_two_numsResponse_<ContainerAllocator1> & lhs, const ::test_service_client::sum_two_numsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_service_client::sum_two_numsResponse_<ContainerAllocator1> & lhs, const ::test_service_client::sum_two_numsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_service_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981739b4699a7cf1b15030371beffb96";
  }

  static const char* value(const ::test_service_client::sum_two_numsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981739b4699a7cf1ULL;
  static const uint64_t static_value2 = 0xb15030371beffb96ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_service_client/sum_two_numsResponse";
  }

  static const char* value(const ::test_service_client::sum_two_numsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 sum\n"
"\n"
"\n"
;
  }

  static const char* value(const ::test_service_client::sum_two_numsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sum_two_numsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_service_client::sum_two_numsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_service_client::sum_two_numsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<double>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERVICE_CLIENT_MESSAGE_SUM_TWO_NUMSRESPONSE_H
